# Generated by Django 2.1.4 on 2018-12-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='fuelprices',
            options={'verbose_name_plural': 'fuel prices'},
        ),
        migrations.AlterModelOptions(
            name='fueltypes',
            options={'verbose_name_plural': 'fuel types'},
        ),
        migrations.AlterModelOptions(
            name='stations',
            options={'verbose_name_plural': 'stations'},
        ),
        migrations.AddField(
            model_name='brands',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
